//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Generated by CleanSwiftGenerator
//

import UIKit

protocol ___VARIABLE_sceneName___PresentationLogic {
    
}

class ___VARIABLE_sceneName___Presenter: ___VARIABLE_sceneName___PresentationLogic {
    // MARK: - Properties
    private weak var viewController: ___VARIABLE_sceneName___DisplayLogic?
    init(viewController: ___VARIABLE_sceneName___DisplayLogic?) {
        self.viewController = viewController
    }
    
}
