//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Generated by CleanSwiftGenerator
//

import UIKit

protocol ___VARIABLE_sceneName___WorkerLogic {
    
}

class ___VARIABLE_sceneName___Worker: ___VARIABLE_sceneName___WorkerLogic {
     let service: SomeNetworkServiceProtocol
    
     init(service: SomeNetworkServiceProtocol) {
         self.service = service
     }

    // MARK: - Methods

}
