//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Generated by CleanSwiftGenerator
//

import UIKit

enum ___VARIABLE_sceneName___Models {
    // MARK: - Use Cases
    enum SomeUseCase {
        struct Request {
            
        }

        struct Response {
            
        }

        struct ViewModel {
        
        }
    }
}
